kinomonstrSpring/src/main/java/com/example/kinomonstr/domain/Contacts.java
package com.example.kinomonstr.domain;

import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;

@Entity
public class Contacts{
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotBlank(message = "vfhuigfyui")
    @Length(max = 2048, message = "svdsyjjyg")
    private String film;
//
    @NotBlank(message = "Заполните название кинотеатра")
    @Length(max = 2048, message = "Message too long (more than 2kB)")
    private String cinema;
//
    @NotBlank(message = "Заполните отзыв")
    @Length(max = 2048, message = "Message too long (more than 2kB)")
    private String otzuv;

   // private String filename;

    @ManyToOne(fetch = FetchType.EAGER) //одному пользователю(user) будет соответствовать много сообщений
    @JoinColumn(name = "user_id")
    private User author;

    public Contacts() {
    }

    public Contacts(String film, String cinema, String otzuv, User author) {
        this.film = film;
        this.cinema = cinema;
        this.otzuv = otzuv;
        this.author = author;
    }

//
//    public Contacts(String film, User author) {
//        this.film = film;
//        this.author = author;
//    }


//    public String getFilename() {
//        return filename;
//    }
//
//    public void setFilename(String filename) {
//        this.filename = filename;
//    }

    public String getAuthorName(){
        return author!=null ? author.getUsername():"<none>";
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFilm() {
        return film;
    }

    public void setFilm(String film) {
        this.film = film;
    }

    public String getCinema() {
        return cinema;
    }

    public void setCinema(String cinema) {
        this.cinema = cinema;
    }

    public User getAuthor() {
        return author;
    }

    public void setAuthor(User author) {
        this.author = author;
    }

    public String getOtzuv() {
        return otzuv;
    }

    public void setOtzuv(String otzuv) {
        this.otzuv = otzuv;
    }
}

kinomonstrSpring/src/main/java/com/example/kinomonstr/controller/ContactController.java
package com.example.kinomonstr.controller;

import com.example.kinomonstr.domain.Contacts;
import com.example.kinomonstr.domain.User;
import com.example.kinomonstr.repos.ContactsRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.UUID;

@Controller
public class ContactController {
    @Value("${upload.path}")    //ищет upload.path в проперти и вставляет его в переменную uploadPath
    private String uploadPath;
    @Autowired
    private ContactsRepo contactsRepo;

    @GetMapping("/contacts")
    public String showContacts(Model model){
//        Iterable<Contacts> listContacts = contactsRepo.findAll();
//        listContacts = contactsRepo.findAll();
//        model.addAttribute("listContacts", listContacts);
        return "contacts";
    }

    @PostMapping("/contacts")
    public String addContacts(@AuthenticationPrincipal User user, @Valid Contacts contacts,
                              BindingResult bindingResult,
                              //список аргументов и ошибок валидации
                              Model model)
                              //@RequestParam("file") MultipartFile file)
           {
        contacts.setAuthor(user);
        if (bindingResult.hasErrors()) {
            Map<String, String> errorsMap = ControllerUtils.getErrors(bindingResult);
            model.mergeAttributes(errorsMap);
            model.addAttribute("message", contacts);
        } else {
            //ЕСЛИ ФАЙЛ НЕ РАВНЯЕТСЯ = 0 ,ТО  МЫ ДОБАВЛЯЕМ ЕГО В КЛАСС
           // saveFile(contacts, file);
            model.addAttribute("message", null); //если валидация прошла успешно, то удаляем сообщ

            contactsRepo.save(contacts);            //СОХРАНЯЕТ ВСЕ В БАЗУ ДАННЫХ
            }

        Iterable<Contacts> listContacts = contactsRepo.findAll();;
        model.addAttribute("listContacts", listContacts);

        return "contacts";
    }

//    private void saveFile(@Valid Contacts message, @RequestParam("file") MultipartFile file) throws IOException {
//        if (file != null && !file.getOriginalFilename().isEmpty()) {
//            File uploadDir = new File(uploadPath);
//
//            if (!uploadDir.exists()) {
//                uploadDir.mkdir();
//            }
//
//            String uuidFile = UUID.randomUUID().toString();
//            String resultFilename = uuidFile + "." + file.getOriginalFilename();
//
//            file.transferTo(new File(uploadPath + "/" + resultFilename));
//
//            message.setFilename(resultFilename);
//        }
//    }

    @PreAuthorize("hasAuthority('ADMIN')")
    @GetMapping("/allcontacts")
    public String allContacts(Model model){
        Iterable<Contacts> listContacts = contactsRepo.findAll();
        listContacts = contactsRepo.findAll();
        model.addAttribute("listContacts", listContacts);

        return "allcontacts";
    }
}

kinomonstrSpring/src/main/java/com/example/kinomonstr/controller/RegistrationController.java
package com.example.kinomonstr.controller;

import com.example.kinomonstr.domain.User;
import com.example.kinomonstr.repos.UserRepo;
import com.example.kinomonstr.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import java.util.Map;

@Controller
public class RegistrationController {
    @Autowired
    private UserService userService;
    @Autowired
    private UserRepo userRepo;

    @GetMapping("/activate/{code}")
    public String activate(Model model, @PathVariable String code) {
        boolean isActivated = userService.activateUser(code);
        if (isActivated) {
            model.addAttribute("message", "User successfully activated");
        } else {
            model.addAttribute("message", "Activation code is not found!");
        }
        return "login";
    }

    @GetMapping("/registration")
    public String userRegistration() {
        return "registration";
    }

    @PostMapping("/registration")
    public String addUser(@Valid User user, BindingResult bindingResult, Model model) {
//        if (user.getPassword() != null && !user.getPassword().equals(user.getPassword2())) {
//            model.addAttribute("passwordError", "Passwords are different!");
//        }

        if (bindingResult.hasErrors()) {
            Map<String, String> errors = ControllerUtils.getErrors(bindingResult);

            model.mergeAttributes(errors);

            return "registration";
        }

        //если не смогли добавтить пользователя в БД, то значит что он существует
        if (!userService.addUser(user)) {
            model.addAttribute("message", "User exists!");
            return "registration";
        }
        return "redirect:/login";
    }

    @GetMapping("/replacePassword")
    public String getNewPassword() {
        return "newPassword";
    }

    @PostMapping("/replacePassword")
    public String updateNewPassword(
            @RequestParam String password, @RequestParam String email, Map<String,Object> model
    ) {
        if (!userService.updatePassword(password, email)) {
            model.put("message", "User not exists!");
            return "newPassword";
        }
        return "redirect:/login";
    }


    //------------------------------            ANDRIOD          ------------------------
//    @GetMapping("/activationKod")
//    public String activate(){
//        return "activationKod";
//    }
//
//      //-----------------------------------       АНДРОИД       ------------------------------------
//    @PostMapping("/activationKod")
//    public String activate(int code, Model model){
//        User user = userRepo.findByActivationCode(code);
//        if(user.getActivationCode()==code){
//            model.addAttribute("message", "Пользователь удачно активировал код");
//            user.setActive(true);
//            userRepo.save(user);
//        }
//        else {
//            model.addAttribute("message", "Код активациии не был найден");
//        }
//        return "redirect:/login";
//    }
}

































//    @GetMapping("/resetToken/{code}")
//    public String activateForPassword(@PathVariable String code) {
//       boolean isActivated = userService.activateUserForPassword(code);
////
////        if (isActivated) {
////            model.addAttribute("message", "User successfully activated");
////        } else {
////            model.addAttribute("message", "Activation code is not found!");
////        }
//        return "newPassword";
//    }

    //запрос с отображением емаила по которому пользователя хочет восстановить пароль
//    @GetMapping("/restorePasswordWithEmail")
//    public String restorePasswordWithEmail(){
//        return "restorePasswordWithEmail";
//    }

    //отправка кода активации на емаил пользователя
//    @PostMapping("/restorePasswordWithEmail")
//    public String postRestorePasswordWithEmail(HttpServletRequest request, Model model, String email){
//        //если не смогли добавтить пользователя в БД, то значит что он существует
//        userService.sendMessageForPassword(email, request);
//        return "redirect:/replacePassword";
//    }
    // Process form submission from forgotPassword page
//    @RequestMapping(value = "/restorePasswordWithEmail", method = RequestMethod.POST)
//    public String processForgotPasswordForm(@RequestParam("email") String userEmail) {
//
//        userService.addNewPassword(userEmail);
//
//        return "redirect:/replacePassword";
//
//    }
    //отображается страница с измененим пароля(установлением нового)
//    @GetMapping("/replacePassword")
//    public String replacePassword(){
//        return "newPassword";
//    }
// Display form to reset password
//    @RequestMapping(value = "/replacePassword", method = RequestMethod.GET)
//    public String displayResetPasswordPage(@RequestParam("token") String token) {
//
//            User user = userService.findUserByResetToken(token);
//
////        Optional<User> user = userService.findUserByResetToken(token);
////
////            model.addAttribute("resetToken", token);
//
//        return "newPassword";
//    }
//    //восстановление пароля
//    @PostMapping("/replacePassword")
//    public String postReplacePassword(
//            @RequestParam Map<String,String> requestParams,
//            @RequestParam String password
////            @RequestParam String email
//    ) {
//        userService.replaceNewPassword(password, requestParams);
//        return "redirect:/login";
//    }
// Process reset password form
//@RequestMapping(value = "/replacePassword", method = RequestMethod.POST)
//public String  setNewPassword(@RequestParam Map<String, String> requestParams) {
//
//    userService.updatePassword(requestParams);
//
//    return "redirect:/login";
//}
    // Going to reset page without a token redirects to login page
//    @ExceptionHandler(MissingServletRequestParameterException.class)
//    public String handleMissingParamss(MissingServletRequestParameterException ex) {
//        return "redirect:/login";
//    }






    //------------------------------            ANDRIOD          ------------------------
//    @GetMapping("/activationKod")
//    public String activate(){
//        return "activationKod";
//    }

    //  -----------------------------------       АНДРОИД       ------------------------------------
//    @PostMapping("/activationKod")
//    public String activate(User user, int code, Model model){
//        if(user.getActivationCode()==code){
//            model.addAttribute("message", "Пользователь удачно активировал код");
//            user.setActive(true);
//            userRepo.save(user);
//        }
//        else {
//            model.addAttribute("message", "Код активациии не был найден");
//        }
//        return "redirect:/login";
//    }

kinomonstrSpring/src/main/resources/templates/activationKod.ftl
<#import "parts/shablonPage.ftl" as shablon/>  <#--для использования шаблона нужно его экспортировать и назначим ему алиас - с-->
<@shablon.mainpage>       <#--при использовании макросов мы используем собаку @  -->

    ${message?ifExists}
    <div class="content">
        <h1>Код активации</h1>
        Введите код который Вам пришел
        <div class="send_otzuv">
            <form method="post" action="/activationKod">
                <input type="text" name="code" placeholder="Введите код">
                <input type="hidden" name="_csrf" value="${_csrf.token}"/>
                <input type="submit" class="login_button" value="Отправить">
            </form>
        </div>
    </div>
</@shablon.mainpage>

kinomonstrSpring/src/main/resources/templates/allcontacts.ftl
<#import "parts/shablonPage.ftl" as shablon/>  <#--для использования шаблона нужно его экспортировать и назначим ему алиас - с-->
<@shablon.mainpage>       <#--при использовании макросов мы используем собаку @  -->
<div class="content">
    <h2>Отзывы о фильмах</h2>

    <#list listContacts as contacts>
        <div class="reviews">
            <div class="review_name">
                ${contacts.authorName}
            </div>
            <div class="review_text">
                Фильм - <i>${contacts.film}</i>
                <br>
                Кинотеатр - <b>${contacts.cinema}</b>
                <br>
                Отзывы - ${contacts.otzuv}
                <#--<div>-->
                    <#--<#if contacts.filename??>-->
                        <#--<img src="/img/${contacts.filename}">-->
                    <#--</#if>-->
                <#--</div>-->
            </div>
        </div>
    <#else>
        No message
    </#list>

</div>
</@shablon.mainpage>

kinomonstrSpring/src/main/resources/templates/contacts.ftl
<#import "parts/shablonPage.ftl" as shablon/>  <#--для использования шаблона нужно его экспортировать и назначим ему алиас - с-->
<@shablon.mainpage>       <#--при использовании макросов мы используем собаку @  -->


<#--<div class="content">-->
    <#--<h1>Отзыв</h1>-->
    <#--Оставьте Ваш отзыв о просмотренном фильме-->
    <#--<div class="send_otzuv">-->
        <#--<form methd="post" action="/contacts">-->
            <#--<input type="text" placeholder="Фильм">-->
            <#--&lt;#&ndash;<input type="text" name="review_name"placeholder="Кинотеатр">&ndash;&gt;-->
            <#--&lt;#&ndash;<textarea name="review_text" placeholder="Отзыв"></textarea>&ndash;&gt;-->
            <#--<input type="submit" class="contact_button" value="Отправить">-->
        <#--</form>-->
    <#--</div>-->
        <#--<br>-->
        <#--<form method="get" action="/allcontacts">-->
            <#--<input type="submit" class="login_button" value="Отзывы">-->
        <#--</form>-->


    <#--<h1>Отзывы пользователей</h1>-->

    <#--<#list messages as message>-->
        <#--<div class="reviews">-->
            <#--&lt;#&ndash;<div class="review_name">&ndash;&gt;-->
                <#--${message.authorName}-->
            <#--&lt;#&ndash;</div>&ndash;&gt;-->
            <#--<div class="review_text">-->
                <#--${message.film}-->
                <#--&lt;#&ndash;${message.cinema}&ndash;&gt;-->
                <#--&lt;#&ndash;${message.otzuv}&ndash;&gt;-->
            <#--</div>-->

        <#--</div>-->
    <#--<#else>-->
        <#--Нет отзывов-->
    <#--</#list>-->
<#--</div>-->



<div class="content">
    <#--<h2>Отзывы</h2>-->
    <#--<#list listContacts as contacts>-->
        <#--<div class="reviews">-->
            <#--<div class="review_name">-->
                <#--${contacts.authorName}-->
            <#--</div>-->
            <#--<div class="review_text">-->
                <#--Фильм - <i>${contacts.film}</i>-->
                <#--<br>-->
                <#--Кинотеатр - <b>${contacts.cinema}</b>-->
                <#--<br>-->
                <#--Отзывы - ${contacts.otzuv}-->
            <#--</div>-->
        <#--</div>-->
    <#--<#else>-->
        <#--No message-->
    <#--</#list>-->

    <div class="send">
        <form method="post">
            <#--<input type="text" name="film" placeholder="Введите фильм" />-->
            <#--<input type="text" name="cinema" placeholder="Введите кинотеатр" />-->
            <#--<input type="text" name="otzuv" placeholder="Введите отзыв" />-->
            <input type="text" name="film" class="{(textError??)?string('is-invalid', '')" value="<#if contacts??>${contacts.film}</#if>" placeholder="Введите фильм" />
            <#if textError??>
                ${textError}
            </#if>
            <input type="text" name="cinema" class="{(textError??)?string('is-invalid', '')" value="<#if contacts??>${contacts.cinema}</#if>" placeholder="Введите кинотеатр" />
            <#if textError??>
                ${textError}
            </#if>
            <input type="text" name="otzuv" class="{(textError??)?string('is-invalid', '')" value="<#if contacts??>${contacts.otzuv}</#if>" placeholder="Введите отзыв" />
            <#if textError??>
                ${textError}
            </#if>
           <#--<input type="file" name="file"/>-->
            <input type="hidden" name="_csrf" value="${_csrf.token}" />
            <input type="submit" value="Добавить">
        </form>

        <form method="get" action="/allcontacts">
             <input type="submit" class="login_button" value="Отзывы">
        </form>
    </div>
</div>

</@shablon.mainpage>

kinomonstrSpring/src/main/resources/templates/file.ftl
<#import "parts/shablonPage.ftl" as shablon/>  <#--для использования шаблона нужно его экспортировать и назначим ему алиас - с-->
<@shablon.mainpage>       <#--при использовании макросов мы используем собаку @  -->
    <div class="content">
        <h2>файлы</h2>

        <#list listContacts as contacts>
                    <div>
                    <#if contacts.filename??>
                    <img src="/img/${contacts.filename}">
                    </#if>
                    </div>
        <#else>
            No message
        </#list>
        <input type="file" name="file"/>
        <input type="hidden" name="_csrf" value="${_csrf.token}" />
        <input type="submit" value="Добавить">


    </div>
</@shablon.mainpage>

kinomonstrSpring/src/main/resources/templates/filmsMorgenPage.ftl
<#import "parts/shablonPage.ftl" as shablon/>  <#--для использования шаблона нужно его экспортировать и назначим ему алиас - с-->
<@shablon.mainpage>       <#--при использовании макросов мы используем собаку @  -->

<div class="content">
            <h1>Моргенштерн</h1>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/a4bL6EQTYJw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

            <div class="info_film_page">
                <span class="label">Рейтинг: </span>
                <span class="value">9.9/10 </span>
                <span class="label">Год: </span>
                <span class="value">2019</span>
                <span class="label">Режисер: </span>
                <span class="value">Алишер Тагирович</span>
            </div>
            <hr>

            <h2>Описание</h2>
            <div class="description_film">
                <img src="morg.jpg">
                Моргеншторн рееееее реккк раааааааа раввв ыууууууупа вппппппп вппппппппп рвааааааааа арввввв риввввввввввввпа ымввввввввввв мыввввввввв вымммммм вмыыыыыыыыы выммммммммммм ывмммммммм выммммммммммм выам вмыыыыыыыыыы вмыыыыыы вымммммммммммвы выпм
            </div>
            <hr>

            <h2>Отзывы о Моргенштерне</h2>

            <#list messages as message>
            <div class="reviews">
                <div class="review_name">
                    ${message.authorName}
                </div>
                <div class="review_text">
                     ${message.text}
                </div>
            </div>
            <#else>
            No message
            </#list>

            <div class="send">
                <form method="post">
                    <input type="text" name="text" class="{(textError??)?string('is-invalid', '')" value="<#if message??>${message.text}</#if>" placeholder="Введите сообщение" />
                    <#if textError??>
                            ${textError}
                    </#if>
                    <input type="hidden" name="_csrf" value="${_csrf.token}" />
                    <input type="submit" value="Добавить">
                </form>
            </div>
        </div>


</@shablon.mainpage>

kinomonstrSpring/src/main/resources/templates/login.ftl
<#import "parts/shablonPage.ftl" as shablon/>  <#--для использования шаблона нужно его экспортировать и назначим ему алиас - с-->
<#import "parts/login.ftl" as l>
<@shablon.mainpage>       <#--при использовании макросов мы используем собаку @  -->
    ${message?ifExists}
    <@l.login "/login" false/>
    <div class="send_otzuv">
        <form method="get" action="/replacePassword">
            <input type="submit" class="login_button" value="Вост пароль">
        </form>
    </div>
</@shablon.mainpage>


    <#--${message?ifExists}-->
<#--<div class="content">-->
            <#--<h1>Вход</h1>-->
            <#--Ввойдите в аккаунт для продолжения пользования сайтом.-->
            <#--<div class="send_otzuv">-->
                <#--&lt;#&ndash;${message?ifExists}&ndash;&gt;-->
                <#--<form method="post" action="/login">-->
                    <#--<input type="text" name="username" placeholder="Введите имя">-->
                    <#--<input type="password" class="login_password" name="password" placeholder="Введите пароль">-->
                    <#--<input type="hidden" name="_csrf" value="${_csrf.token}"/>-->
                    <#--<input type="submit" class="login_button" value="Войти">-->
                    <#--<a href="/replacePassword">Восстановить пароль</a>-->
                <#--</form>-->

            <#--</div>-->

    <#--<div class="send_otzuv">-->
        <#--<form method="get" action="/replacePassword">-->
            <#--<input type="submit" class="login_button" value="Вост пароль">-->
        <#--</form>-->
    <#--</div>-->
<#--</div>-->
<#--</@shablon.mainpage>-->




<#--<div>-->
    <#--Login page-->
    <#--<form action="/login" method="post">-->
        <#--<div><label> User Name : <input type="text" name="username"/> </label></div>-->
        <#--<div><label> Password: <input type="password" name="password"/> </label></div>-->
        <#--<input type="hidden" name="_csrf" value="${_csrf.token}"/>-->
        <#--<div><input type="submit" value="Войти"/></div>-->
    <#--</form>-->
    <#--<a href="/registration">Регистрация</a>-->
<#--</div>-->

kinomonstrSpring/src/main/resources/templates/newPassword.ftl
<#import "parts/shablonPage.ftl" as shablon/>  <#--для использования шаблона нужно его экспортировать и назначим ему алиас - с-->
<@shablon.mainpage>       <#--при использовании макросов мы используем собаку @  -->


    ${message?ifExists}
    <div class="content">
        <h1>Восстановление пароля</h1>
        Введите новый пароль
        <div class="send_otzuv">
            <form method="post" action="/replacePassword">
                <input type="password" class="login_password" name="password" placeholder="Введите пароль">
                <input type="email" name="email" placeholder="some@gmail.com">
                <#--<input type="password" class="login_password" name="password" placeholder="Повторите пароль">-->
                <input type="hidden" name="_csrf" value="${_csrf.token}"/>
                <input type="submit" class="regis_button" value="Сменить пароль">
            </form>
        </div>
    </div>


</@shablon.mainpage>

kinomonstrSpring/src/main/resources/templates/profile.ftl
<#import "parts/shablonPage.ftl" as shablon/>  <#--для использования шаблона нужно его экспортировать и назначим ему алиас - с-->
<@shablon.mainpage>       <#--при использовании макросов мы используем собаку @  -->

${message?ifExists}

<div class="content">
    <h1>Профиль</h1>
    Введите данные, которые Вы хотите изменить!
    <div class="send_otzuv">
        <form method="post" action="/profile">
            <#--<input type="text" name="username" placeholder="Введите имя">-->
            <input type="email" name="email" placeholder="some@gmail.com">
            <input type="password" class="login_password" name="password" placeholder="Введите пароль">
            <input type="hidden" name="_csrf" value="${_csrf.token}"/>
            <input type="submit" class="regis_button" value="Изменить">
        </form>
    </div>
</div>


</@shablon.mainpage>

kinomonstrSpring/src/main/resources/templates/registration.ftl
<#import "parts/shablonPage.ftl" as shablon/>  <#--для использования шаблона нужно его экспортировать и назначим ему алиас - с-->
<#import "parts/login.ftl" as l>
<@shablon.mainpage>       <#--при использовании макросов мы используем собаку @  -->
    ${message?ifExists}
    <@l.login "/registration" true />
</@shablon.mainpage>

    <#--${message?ifExists}-->
<#--<div class="content">-->
                <#--<h1>Регистрация</h1>-->
                <#--Пройдите регистрацию, ради того чтобы получить все преимущества пользования сайтом!-->
                <#--<div class="send_otzuv">-->
                    <#--<form method="post" action="/registration">-->
                        <#--<input type="text" name="username" placeholder="Введите имя">-->
                        <#--<input type="email" name="email" placeholder="some@gmail.com">-->
                        <#--<input type="password" class="login_password" name="password" placeholder="Введите пароль">-->
                        <#--&lt;#&ndash;<input type="password" class="login_password" name="password2" placeholder="Повторите пароль">&ndash;&gt;-->
                        <#--<input type="hidden" name="_csrf" value="${_csrf.token}"/>-->
                        <#--<input type="submit" class="regis_button" value="Зарегистрироваться">-->
                    <#--</form>-->
                <#--</div>-->
            <#--</div>-->


<#--</@shablon.mainpage>-->


<#--Add new user-->

<#--<form action="/registration" method="post">-->
    <#--<div><label> User Name : <input type="text" name="username"/> </label></div>-->
    <#--<div><label> Password: <input type="password" name="password"/> </label></div>-->
    <#--<input type="hidden" name="_csrf" value="${_csrf.token}"/>-->
    <#--<div><input type="submit" value="Sign In"/></div>-->
<#--</form>-->

kinomonstrSpring/src/main/resources/templates/restorePasswordWithEmail.ftl
<#import "parts/shablonPage.ftl" as shablon/>  <#--для использования шаблона нужно его экспортировать и назначим ему алиас - с-->
<@shablon.mainpage>       <#--при использовании макросов мы используем собаку @  -->

    <div class="content">
        <h1>Восстановление пароля</h1>
        Введите свою почту чтобы восстановить пароль
        <div class="send_otzuv">
            <form method="post" action="/restorePasswordWithEmail">
                <input type="email" name="email" placeholder="some@gmail.com">
                <input type="hidden" name="_csrf" value="${_csrf.token}"/>
                <input type="submit" class="login_button" value="Вост пароль">
            </form>
        </div>
    </div>


</@shablon.mainpage>